To build &amp; run with Maven:

----
./mvnw package && java -jar target/dynamic-query-0.1.0.jar
----

To build &amp; run with Docker:

----
docker build -t com.telenor/dynamic-query .
docker run -p 8080:8080 com.telenor/dynamic-query
----

To build a Docker Image with Maven

----
./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=com.telenor/dynamic-query
----

'''

To check application is up and running go to http://localhost:8080 to see message

----
"Welcome to Telenor's take-home assignment: Dynamic Query"
----

To check for available phones go to sample url below

http://localhost:8080/products?productType=phone&max_price=1000&productProperty:color=grön&city=Stockholm

To check for available subscriptions go to sample url below

http://localhost:8080/products?productType=subscription&productProperty:gb_limit_min=10&city=Karlskrona

'''

----
GET /products

Query Parameter			        Description
----------------------------    ---------------------------------------------------------------
productType					    The restProduct productType. (String 'phone' or 'subscription')
min_price				        The minimum price in SEK. (Number)
max_price				        The maximum price in SEK. (Number)
city					        The city in which a store is located. (String)
productProperty				    The name of the productProperty. (String 'color' or 'gb_limit')
productProperty:color			The color of the phone. (String)
productProperty:gb_limit_min 	The minimum GB limit of the subscription. (Number)
productProperty:gb_limit_max 	The maximum GB limit of the subscription. (Number)
----

The expected response is a JSON array with the products in a 'data' wrapper. 

Example: GET /products?productType=subscription&max_price=1000&city=Stockholm
----
{
	data: [
		{
		    productType: 'subscription',
		    properties: 'gb_limit:10',
		    price: '704.00',
		    store_address: 'Dana gärdet, Stockholm'
	  	},
	  	{
		    productType: 'subscription',
		    properties: 'gb_limit:10',
		    price: '200.00',
		    store_address: 'Octavia gränden, Stockholm'
	  	}
	]
}
----
'''
To access swagger-ui go to following url

http://localhost:8080/swagger-ui/#/product-controller/


To access the database using h2 console go to following url

http://localhost:8080/h2-console/

'''

----
Please Note: Query parameter 'productProperty' seemed redundant, so has not been used in the implementation. But has been included to comply with the contract.
----